# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 645685b445b600d43ab8a1356aff19fb289a7869f96b947d3d6aff0f5483950bf1b141e8addb1680abb19cacc6cd865a3792a12e1937d024184a179abf58619f

test:
  secret_key_base: 867fc61a246ad567e36ced9256e6000452f377e8ea64b114a646de1a9a2f2cd5f8420adc64fa960d5a15beda88aaf23cdce807ecb9d28b1dc5f75bff3ad15142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
